apiVersion: v1

kind: ConfigMap
metadata:
  name: influxdb-config
data:
  influxdb.conf: |+
  
    [meta]
      dir = "/var/lib/influxdb/meta"
      
    [data]
      dir = "/var/lib/influxdb/data"

      wal-dir = "/var/lib/influxdb/wal"
      
      series-id-set-cache-size = 100
      
    [http]
      enabled = true
 
